# Generated by Django 5.2 on 2025-04-09 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('royhatga_olingan_sana', models.DateField(verbose_name="Ro'yhatga olingan sana")),
                ('tugallangan_sana', models.DateField(verbose_name='Tugallangan sana')),
                ('tibbiy_muassasa_nomi', models.CharField(max_length=255, verbose_name='Tibbiy muassasa nomi')),
                ('fish', models.CharField(max_length=255, verbose_name='FISH')),
                ('jinsi', models.CharField(choices=[('erkak', 'Erkak'), ('ayol', 'Ayol')], max_length=10, verbose_name='Jinsi')),
                ('pasport_jshshir', models.CharField(max_length=30, verbose_name='Pasport JSHSHIR')),
                ('yosh', models.PositiveIntegerField(verbose_name='Yosh')),
                ('manzil', models.TextField(verbose_name='Manzil')),
                ('kasallik_turi', models.CharField(max_length=255, verbose_name='Kasallik turi')),
                ('davolovchi_shifokor', models.CharField(max_length=255, verbose_name='Davolovchi shifokor ismi')),
                ('bolim_boshligi', models.CharField(max_length=255, verbose_name='Bo‘lim boshlig‘i ismi')),
            ],
        ),
    ]
