# Generated by Django 5.2 on 2025-04-11 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spravka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('royxat_sana', models.DateField(verbose_name="Ro'yxatga olingan sana")),
                ('tugash_sana', models.DateField(verbose_name='Tugallangan sana')),
                ('muassasa_nomi', models.CharField(max_length=255)),
                ('fish', models.CharField(max_length=255)),
                ('jinsi', models.CharField(choices=[('erkak', 'Erkak'), ('ayol', 'Ayol')], max_length=10)),
                ('jshshir', models.CharField(max_length=14)),
                ('yosh', models.PositiveIntegerField()),
                ('manzil', models.TextField()),
                ('kasallik_turi', models.CharField(max_length=255)),
                ('shifokor', models.CharField(max_length=255)),
                ('bolim_boshligi', models.CharField(max_length=255)),
                ('parol', models.CharField(blank=True, help_text='4 xonali raqamli parol. Agar kiritilmasa, avtomatik yaratiladi.', max_length=4, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
