# Generated by Django 5.2 on 2025-04-11 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_spravka_delete_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spravka',
            name='jinsi',
            field=models.CharField(choices=[('Erkak', 'Erkak'), ('Ayol', 'Ayol')], max_length=10),
        ),
    ]
